version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      gotk4:
        patterns:
          - "github.com/diamondburned/gotk4*"
      hashicorp:
        patterns:
          - "github.com/hashicorp/*"
      minor-and-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
